### ISSUE TITLE
 java.lang.NullPointerException: Layout parameters cannot be null

### ISSUE THREAD

**Issue by LoveqLRC** [nukc/StateView#20]
```  
  java.lang.NullPointerException: Layout parameters cannot be null
        at android.view.View.setLayoutParams(View.java:16109)
        at com.github.nukc.stateview.StateView.inject(StateView.java:131)
        at com.github.nukc.stateview.StateView.inject(StateView.java:235)
```

**Comment by windwise** [comment]
我也遇到这个问题，请问你怎么解决的？

**Comment by nukc** [comment]
@windwise #28
