### ISSUE TITLE
使用Butterknife注解绑定最外层ViewGroup后，将ViewGroup注入stateView，不显示状态页面

### ISSUE THREAD

**Issue by zljt1314** [nukc/StateView#23]
代码如下：
public class FAQFragment extends BaseFragment {
    @BindView(R.id.faq_ll_root)
    LinearLayout mLl;
    @BindView(R.id.txt)
    TextView textView;
    private StateView stateView;

    /**
     * 相当于onCreateView()
     *
     * @return
     */
    @Override
    public View initView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        return inflater.inflate(R.layout.fragment_answer_doubt_faq, container, false);
    }

    /**
     * 相当于onActivityCreate()
     */
    @Override
    public void initData(@Nullable Bundle savedInstanceState) {
        stateView = StateView.inject(mLl);
        stateView.showRetry();
    }
}

除了将inject()放在oncreatView()中还有没有其他解决方案

如果将此fragment作为viewpager的子项，滑动超出两个报错。报错如下：
 java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.unFocus(android.view.View)' on a null object reference
        at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5304)
        at android.view.ViewGroup.removeViewAt(ViewGroup.java:5267)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1771)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:792)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2215)
        at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
        at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
        at android.view.View.layout(View.java:19812)
        at android.view.ViewGroup.layout(ViewGroup.java:6154)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
        at android.view.View.layout(View.java:19828)
        at android.view.ViewGroup.layout(ViewGroup.java:6154)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19828)
        at android.view.ViewGroup.layout(ViewGroup.java:6154)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19828)
        at android.view.ViewGroup.layout(ViewGroup.java:6154)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19828)
        at android.view.ViewGroup.layout(ViewGroup.java:6154)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19828)
        at android.view.ViewGroup.layout(ViewGroup.java:6154)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:765)
        at android.view.View.layout(View.java:19828)
        at android.view.ViewGroup.layout(ViewGroup.java:6154)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2627)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2332)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1468)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7045)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:918)
        at android.view.Choreographer.doCallbacks(Choreographer.java:730)
        at android.view.Choreographer.doFrame(Choreographer.java:662)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:904)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6627)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by nukc** [comment]
看错误是报 NullPointerException，可以排查下

**Comment by zljt1314** [comment]
> 看错误是报NullPointerException，可以排查下

好的，我这边查了大半天，没找到问题 = =

**Comment by zljt1314** [comment]
目前这样是可以解决这个问题的，之前那样做不知道为什么会出现问题。
public class FAQFragment extends BaseFragment {
    //    @BindView(R.id.faq_ll_root)
    LinearLayout mLl;
    @BindView(R.id.txt)
    TextView textView;
    private StateView stateView;

    /**
     * 相当于onCreateView()
     *
     * @return
     */
    @Override
    public View initView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_answer_doubt_faq, container, false);
        mLl = view.findViewById(R.id.faq_ll_root);
        stateView = StateView.inject(mLl);
        return view;
    }

    /**
     * 相当于onActivityCreate()
     */
    @Override
    public void initData(@Nullable Bundle savedInstanceState) {
        stateView.showRetry();
    }
}

**Comment by nukc** [comment]
结合下生命周期看看
