### ISSUE TITLE
NoClassDefFoundError both 1.5.4v &2.1.1v 

### ISSUE THREAD

**Issue by windyer39** [nukc/StateView#34]
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/constraintlayout/widget/ConstraintLayout;
        at com.github.nukc.stateview.StateView.addToParent(StateView.kt:279)
        at com.github.nukc.stateview.StateView.inflate(StateView.kt:251)
        at com.github.nukc.stateview.StateView.showView(StateView.kt:147)
        at com.github.nukc.stateview.StateView.showLoading(StateView.kt:127)

   Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.constraintlayout.widget.ConstraintLayout$LayoutParams" on path: DexPathList[[zip file "/data/app/com.xxxx-ozFpwn3RnL8tk4kfS5iEMg==/base.apk"],nativeLibraryDirectories=[/data/app/com.xxxx-ozFpwn3RnL8tk4kfS5iEMg==/lib/arm64, /system/lib64, /hw_product/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:209)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)

**Comment by nukc** [comment]
implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
缺少依赖 constraintlayout，最新 2.0 版本也已出

**Comment by nukc** [comment]
@windyer39 2.2.0 版本可以不依赖 constraintlayout
