### ISSUE TITLE
kotlin.TypeCastException Crash

### ISSUE THREAD

**Issue by omkar-tenkale** [nukc/StateView#43]
kotlin.TypeCastException: null cannot be cast to non-null type android.view.ViewGroup
        at com.github.nukc.stateview.StateView.showView(StateView.kt:155)
        at com.github.nukc.stateview.StateView.showEmpty(StateView.kt:123)
        
        Occurs when retryView is set

**Comment by nukc** [comment]
need more log info, StateFView version, please check your retryView
